### ISSUE TITLE
Adding select option for rows or checkbox column

### ISSUE THREAD

**Issue by shimwell** [aknarts/yew-custom-components#1]
Awesome to see this repo, the examples look great. I'm just getting started in Rust but one think I would really like to try and add are selectable row. Perhaps via a checkbox or something like that.

- [x] check

I shall have a go at installing this locally and see if my rust skills are up to the task.

**Comment by aknarts** [comment]
You want this on the table? Do you have an example of how this works from somewhere? Technically, I think it can be done already.

Yew does not make this very straight forward, you cannot pass data from a component to its parent.

The way I would handle this is to put a callback into the TableData object and handle the selections in the parent, I can throw it into the example if that would be helpful.

**Comment by aknarts** [comment]
It is a similar situation with removing the rows. Essentially table is there to just display the data, any actions need to be handled outside the table component itself.

**Comment by shimwell** [comment]
Yes I would be keen to put a column of checkboxes on the left hand side. Here is how it could look when made with plotly and dash [slow to load](http://isotope-plotter.xsplot.com/). Londer term I'm hoping to remake this website of mine in Yew and Rust and the table is a major part.

**Comment by aknarts** [comment]
I will throw it into the example, it makes sense to have an "active" table in there as well. I should also comment on the code, so it is clear what part does what.

Coincidentally, I just did a graph on one of my projects as well, your project is certainly doable.

**Comment by aknarts** [comment]
https://aknarts.github.io/yew-custom-components/#/table

Threw it in the example. I hope it matches what you imagined.

**Comment by shimwell** [comment]
Amazing, this is ideal. I shall close this issue now. Many many thanks for making nice examples.

Good luck with the package name.
