### ISSUE TITLE
Adding pagination to the table example

### ISSUE THREAD

**Issue by shimwell** [aknarts/yew-custom-components#3]
I did a quick search and grep through the source code to see if it was possible to make the table component paginate for large tables.

I'm not sure of the best option for pagination but adding buttons or links like this would be helpful for large tables. There could be better ways with dropdown boxes.

![](https://www.jqueryscript.net/images/Tiny-jQuery-Pagination-Widget-For-HTML-Table-table-hpaging.jpg)

**Comment by aknarts** [comment]
Ok, so I though this could be again handled outside the table component, but with sorting, it makes sense for the table to hold all the data so you can sort through all of it. I will look into adding it inside, need to figure out how to best do it.

**Comment by aknarts** [comment]
Added pagination to the table and pagination component, one thing that I need to probably start thinking about is internationalization.  I now hardcoded "Previous" and "Next" ... But the pagination component is pretty much just an example how this can be done and is not mandatory, it can be handled in multiple ways.
